spring.application.name=PlataformaEducativa

# Configuracion Database Oracle (wallet)
spring.datasource.url=jdbc:oracle:thin:@testdb1_high
spring.datasource.username=LEARNINGPLATFORM
spring.datasource.password=Springboot.2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=/Users/franc/Downloads/wallet/Wallet_TESTDB1

# Ajustes recomendados HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true