spring.application.name=PlataformaEducativa

# Configuracion Database Oracle (wallet)
spring.datasource.url=jdbc:oracle:thin:@testdb1_high
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=/wallet

# Ajustes recomendados HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# S3
aws.region=us-east-1
aws.s3.bucket-name=cloud-plataforma-educativa
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN}

# DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
